### ISSUE TITLE
GIF should show election guide

### ISSUE THREAD

**Issue by asraam** [thechicagoreporter/electoraid#29]
A GIF clicking through races and candidates would showcase the functionality and core features of Chi.Vote better than the landing page.

**Comment by oobineme** [comment]
Thanks for flagging this, Asraa. The purpose of the site is to be a platform supplement for TCR when speaking with prospective users of Electoraid. They really shouldn't be going down that far because they would have talked with TCR beforehand. On the chance that they see it via word-of-mouth, they should be prompted to just click on the Chi.Vote link in the copy.
